# Generated by Django 4.1.1 on 2022-10-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alokairu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kotxe',
            name='alokatua',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kotxe',
            name='bukaeradata',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kotxe',
            name='hasieradata',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
